// ux.js
function initUX(){
  renderAvatar(); renderCurrencies(); renderSagas(); bindActions(); renderPanelContent('dashboard');
}
function bindActions(){
  document.getElementById('menu-toggle').onclick = ()=> toggleSide();
  document.getElementById('btn-save').onclick = ()=> { saveState(AGIL.state); toast('Guardado'); };
  document.getElementById('btn-new-saga').onclick = ()=> createSagaPrompt();
  document.getElementById('btn-create').onclick = ()=> openTaskModal();
  document.getElementById('modal-close').onclick = closeModal;
  document.getElementById('task-form').onsubmit = (e)=>{ e.preventDefault(); saveTaskFromModal(); };
  document.getElementById('btn-delete').onclick = deleteTaskFromModal;
}
function toast(msg){ const t = document.createElement('div'); t.className='toast'; t.textContent=msg; Object.assign(t.style,{position:'fixed',left:'50%',transform:'translateX(-50%)',bottom:'18px',background:'#111',color:'#fff',padding:'8px 12px',borderRadius:'8px',opacity:0.95}); document.body.appendChild(t); setTimeout(()=>t.remove(),1200); }
function toggleSide(){ document.getElementById('side').classList.toggle('hidden'); }
function renderAvatar(){ const el=document.getElementById('avatar-card'); if(!el) return; const a=AGIL.state.profile.avatar; el.innerHTML = '<div style="text-align:center"><div style="width:72px;height:72px;border-radius:10px;background:rgba(255,255,255,0.02);display:inline-flex;align-items:center;justify-content:center">'+avatarSVG(a)+'</div><div class="small" style="margin-top:6px"><strong>'+a.name+'</strong></div><div class="small">'+a.role+' · '+a.race+'</div></div>'; }
function avatarSVG(p){ const skinPal=['#f5d7c4','#ffd8b8','#f2e9d7','#e7f5ff','#fbe7ff']; const hairPal=['#2f2f2f','#443a9e','#b3477a','#3a8f6b','#000000']; const skin=skinPal[(p.skin||0)%skinPal.length]; const hair=hairPal[(p.hair||0)%hairPal.length]; return '<svg width="48" height="48" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg"><circle cx="60" cy="40" r="22" fill="'+skin+'"/><path d="M38 36 q22 -26 44 0 q-6 6 -22 6 q-16 0 -22 -6" fill="'+hair+'"/></svg>'; }
function renderCurrencies(){ document.getElementById('coinA').textContent = AGIL.state.currencies.coinA||0; document.getElementById('coinB').textContent = AGIL.state.currencies.coinB||0; document.getElementById('coinC').textContent = AGIL.state.currencies.coinC||0; }
function renderSagas(){ const root=document.getElementById('saga-list'); if(!root) return; root.innerHTML=''; if(!AGIL.state.sagas.length){ root.innerHTML='<div class="small">No hay Sagas. Crea la primera para organizar tus misiones.</div>'; return; } AGIL.state.sagas.forEach(s=>{ const card=document.createElement('div'); card.className='saga-card'; card.innerHTML = '<div style="display:flex;justify-content:space-between;align-items:center"><div><strong>'+s.name+'</strong><div class="small">'+(s.metas?.length||0)+' metas</div></div><div style="display:flex;gap:6px"><button class="btn small" data-sid="'+s.id+'" onclick="promptMeta(\''+s.id+'\')">+Meta</button><button class="btn small" onclick="renameSaga(\''+s.id+'\')">✎</button><button class="btn small" onclick="deleteSaga(\''+s.id+'\')">🗑</button></div></div>'; (s.metas||[]).forEach(m=>{ const mEl=document.createElement('div'); mEl.className='meta-card'; mEl.innerHTML = '<div style="display:flex;justify-content:space-between"><div><strong>'+m.title+'</strong><div class="small">'+(m.tasks?.length||0)+' tareas</div></div><div style="display:flex;gap:6px"><button class="btn small" onclick="openTaskModal(\''+s.id+'\',\''+m.id+'\')">+Tarea</button><button class="btn small" onclick="renameMeta(\''+s.id+'\',\''+m.id+'\')">✎</button></div></div>'; (m.tasks||[]).forEach(t=>{ const ti=document.createElement('div'); ti.className='task-item'; ti.innerHTML = '<div class="task-left"><div style="width:10px;height:10px;border-radius:4px;background:'+(t.type==='consequence'?'#e06':'#6b5dd3')+'"></div><div style="margin-left:8px"><div style="font-weight:600">'+t.title+'</div><div class="small">'+(t.priority||'')+' · '+(t.due||'')+'</div></div></div><div style="display:flex;gap:6px"><button class="btn small" onclick="completeTask(\''+t.id+'\')">✓</button><button class="btn small" onclick="editTask(\''+t.id+'\')">✎</button><button class="btn small" onclick="removeTask(\''+t.id+'\')">🗑</button></div>'; mEl.appendChild(ti); }); card.appendChild(mEl); }); root.appendChild(card); }); }
function createSagaPrompt(){ const name = prompt('Nombre de la nueva Saga:'); if(!name) return; AGIL.state.sagas.push({ id:'saga_'+Math.random().toString(36).slice(2,6), name, metas:[]}); saveState(AGIL.state); renderSagas(); toast('Saga creada'); }
function promptMeta(sid){ const name = prompt('Nombre de la Meta:'); if(!name) return; const saga = AGIL.state.sagas.find(x=>x.id===sid); saga.metas = saga.metas || []; saga.metas.push({ id:'meta_'+Math.random().toString(36).slice(2,6), title:name, desc:'', tasks:[]}); saveState(AGIL.state); renderSagas(); toast('Meta creada'); }
function renameSaga(sid){ const s=AGIL.state.sagas.find(x=>x.id===sid); const nm=prompt('Nuevo nombre:',s.name); if(!nm) return; s.name=nm; saveState(AGIL.state); renderSagas(); }
function deleteSaga(sid){ if(!confirm('Eliminar saga y todo su contenido?')) return; AGIL.state.sagas = AGIL.state.sagas.filter(x=>x.id!==sid); saveState(AGIL.state); renderSagas(); toast('Saga eliminada'); }
function renameMeta(sid,mid){ const m=findMeta(mid); const nm=prompt('Nuevo nombre:',m.title); if(!nm) return; m.title=nm; saveState(AGIL.state); renderSagas(); }
function openTaskModal(sid='',mid=''){ const modal=document.getElementById('modal'); modal.classList.remove('hidden'); document.getElementById('modal-title').textContent='Crear tarea'; const sagaSel=document.getElementById('task-saga'); sagaSel.innerHTML='<option value="">Sin saga</option>'; AGIL.state.sagas.forEach(s=>{ const opt=document.createElement('option'); opt.value=s.id; opt.textContent=s.name; sagaSel.appendChild(opt); }); const metaSel=document.getElementById('task-meta'); metaSel.innerHTML='<option value="">Sin meta</option>'; AGIL.state.sagas.forEach(s=> (s.metas||[]).forEach(m=>{ const opt=document.createElement('option'); opt.value=m.id; opt.textContent=s.name+' → '+m.title; metaSel.appendChild(opt); })); if(sid) document.getElementById('task-saga').value=sid; if(mid) document.getElementById('task-meta').value=mid; document.getElementById('task-type').value='mission'; document.getElementById('task-title').value=''; document.getElementById('task-desc').value=''; document.getElementById('task-priority').value='med'; document.getElementById('task-due').value=''; document.getElementById('task-rew-A').value='0'; document.getElementById('task-rew-B').value='0'; document.getElementById('task-rew-C').value='0'; document.getElementById('btn-delete').style.display='none'; modal.dataset.edit=''; }
function closeModal(){ const modal=document.getElementById('modal'); modal.classList.add('hidden'); modal.dataset.edit=''; }
function saveTaskFromModal(){ const modal=document.getElementById('modal'); const eid=modal.dataset.edit; const type=document.getElementById('task-type').value; const sagaId=document.getElementById('task-saga').value; const metaId=document.getElementById('task-meta').value; const title=document.getElementById('task-title').value.trim(); if(!title){ alert('Escribe un título'); return; } const desc=document.getElementById('task-desc').value; const priority=document.getElementById('task-priority').value; const due=document.getElementById('task-due').value; const rewards={A:Number(document.getElementById('task-rew-A').value||0),B:Number(document.getElementById('task-rew-B').value||0),C:Number(document.getElementById('task-rew-C').value||0)}; if(eid){ const t=findTask(eid); if(!t) return; Object.assign(t,{type,title,desc,priority,due,rewards}); saveState(AGIL.state); renderSagas(); closeModal(); toast('Tarea actualizada'); return; } const newTask={ id:'task_'+Math.random().toString(36).slice(2,6), type, title, desc, priority, due, rewards, done:false }; if(metaId){ const m=findMeta(metaId); m.tasks=m.tasks||[]; m.tasks.push(newTask); } else if(sagaId){ const saga=AGIL.state.sagas.find(s=>s.id===sagaId); const newMeta={ id:'meta_'+Math.random().toString(36).slice(2,6), title:'Meta auto', desc:'', tasks:[newTask] }; saga.metas=saga.metas||[]; saga.metas.push(newMeta); } else { const s={ id:'saga_'+Math.random().toString(36).slice(2,6), name:title, metas:[{id:'meta_'+Math.random().toString(36).slice(2,6), title:'Meta inicial', tasks:[newTask]}] }; AGIL.state.sagas.push(s); } saveState(AGIL.state); renderSagas(); closeModal(); toast('Tarea creada'); }
function findMeta(mid){ for(const s of AGIL.state.sagas) for(const m of (s.metas||[])) if(m.id===mid) return m; return null; }
function findTask(tid){ for(const s of AGIL.state.sagas) for(const m of (s.metas||[])) for(const t of (m.tasks||[])) if(t.id===tid) return t; return null; }
function editTask(tid){ openTaskModal(); setTimeout(()=>{ document.getElementById('modal').dataset.edit=tid; editTaskPopulate(tid); },30); }
function editTaskPopulate(tid){ const t=findTask(tid); if(!t) return; document.getElementById('task-type').value=t.type; document.getElementById('task-title').value=t.title; document.getElementById('task-desc').value=t.desc||''; document.getElementById('task-priority').value=t.priority||'med'; document.getElementById('task-due').value=t.due||''; document.getElementById('task-rew-A').value=t.rewards?.A||0; document.getElementById('task-rew-B').value=t.rewards?.B||0; document.getElementById('task-rew-C').value=t.rewards?.C||0; document.getElementById('btn-delete').style.display='inline-block'; }
function deleteTaskFromModal(){ const modal=document.getElementById('modal'); const id=modal.dataset.edit; if(!id) return; if(!confirm('Eliminar esta tarea?')) return; for(const s of AGIL.state.sagas){ for(const m of (s.metas||[])){ m.tasks=(m.tasks||[]).filter(t=>t.id!==id); } } saveState(AGIL.state); renderSagas(); closeModal(); toast('Tarea eliminada'); }
function removeTask(tid){ if(!confirm('Eliminar tarea?')) return; for(const s of AGIL.state.sagas) for(const m of (s.metas||[])) m.tasks=(m.tasks||[]).filter(t=>t.id!==tid); saveState(AGIL.state); renderSagas(); toast('Eliminada'); }
function completeTask(tid){ const t=findTask(tid); if(!t) return; if(t.done) return alert('Ya completada'); t.done=true; AGIL.state.currencies.coinA += t.rewards?.A||0; AGIL.state.currencies.coinB += t.rewards?.B||0; AGIL.state.currencies.coinC += t.rewards?.C||0; awardRandomXP(12); saveState(AGIL.state); renderSagas(); renderCurrencies(); toast('Completada'); }
function awardRandomXP(amount){ const keys=Object.keys(AGIL.state.skills); if(!keys.length) return; const id=keys[Math.floor(Math.random()*keys.length)]; AGIL.state.skills[id].xp=(AGIL.state.skills[id].xp||0)+amount; const need=xpForLevel(AGIL.state.skills[id].level,AGIL.state.skills[id].tier); while(AGIL.state.skills[id].xp>=need && AGIL.state.skills[id].level<20){ AGIL.state.skills[id].xp-=need; AGIL.state.skills[id].level++; } if(AGIL.state.skills[id].level>=20){ AGIL.state.skills[id].level=0; AGIL.state.skills[id].tier=Math.min((AGIL.state.skills[id].tier||0)+1,6); AGIL.state.currencies.coinB += 1; } saveState(AGIL.state); }
function xpForLevel(level,tier){ const base=20+(level*12); const mult=1+(tier*0.45); return Math.round(base*mult); }
function renderPanelContent(key){ const pc=document.getElementById('panel-content'); if(key==='dashboard'){ pc.innerHTML=''; return; } if(key==='inventory'){ const out=['<div class="panel"><h3>Inventario</h3><div class="inventory-list">']; (AGIL.state.inventory.items||[]).forEach(it=> out.push('<div class="inventory-item"><strong>'+it.name+'</strong><div class="small">'+it.category+' · '+it.tier+'</div><div class="small">'+it.effect+'</div><div style="margin-top:8px"><button class="btn small" onclick="equipItem(\''+it.uid+'\')">Equipar</button> <button class="btn small" onclick="dropItem(\''+it.uid+'\')">Eliminar</button></div></div>')); out.push('</div></div>'); pc.innerHTML=out.join(''); return; } if(key==='skills'){ const sections = AGIL.skillDef.categories.map(cat=>{ const rows = cat.skills.map(s=>{ const st=AGIL.state.skills[s.id]||{level:0,tier:0}; const pct=Math.round((st.level/20)*100); return '<div class="skill-row"><div><strong>'+s.name+'</strong><div class="small">'+(s.desc||'')+'</div></div><div style="text-align:right"><div style="width:140px;background:rgba(255,255,255,0.03);height:10px;border-radius:6px;overflow:hidden"><div style="width:'+pct+'%;height:100%;background:linear-gradient(90deg,var(--accent),var(--accent-2))"></div></div><div class="small">Lvl '+st.level+' · '+tierName(st.tier)+'</div></div></div>'; }).join(''); return '<div class="panel"><h3>'+cat.name+'</h3>'+rows+'</div>'; }).join(''); pc.innerHTML=sections; return; } }
function equipItem(uid){ const it=AGIL.state.inventory.items.find(x=>x.uid===uid); if(!it) return; AGIL.state.inventory.equipped[it.category]=it; saveState(AGIL.state); toast('Equipado'); renderAvatar(); }
function dropItem(uid){ AGIL.state.inventory.items = AGIL.state.inventory.items.filter(x=>x.uid!==uid); saveState(AGIL.state); renderPanelContent('inventory'); toast('Eliminado'); }
function editTask(tid){ openTaskModal(); setTimeout(()=>{ document.getElementById('modal').dataset.edit=tid; editTaskPopulate(tid); },30); }
function editTaskPopulate(tid){ const t=findTask(tid); if(!t) return; document.getElementById('task-type').value=t.type; document.getElementById('task-title').value=t.title; document.getElementById('task-desc').value=t.desc||''; document.getElementById('task-priority').value=t.priority||'med'; document.getElementById('task-due').value=t.due||''; document.getElementById('task-rew-A').value=t.rewards?.A||0; document.getElementById('task-rew-B').value=t.rewards?.B||0; document.getElementById('task-rew-C').value=t.rewards?.C||0; document.getElementById('btn-delete').style.display='inline-block'; }
function tierName(t){ const names=['Aspirante','Iniciado','Adepto','Virtuoso','Maestro','Ascendido','Eterno']; return names[t]||names[0]; }
